### ISSUE TITLE
Expired SSL certificates

### ISSUE THREAD

**Issue by ilya-zlobintsev** [jkuri/bore#13]
The certificates of https://bore.network/ are expired since 05/02/2022.

**Comment by adierebel** [comment]
i think the project is abandoned

**Comment by jkuri** [comment]
its not abandoned, I don't have currently server instance to host this.

**Comment by dustyroberts** [comment]
Make use of oracle cloud (free tier)

**Comment by jkuri** [comment]
hi, I re-established `bore` server and it is now running on https://bore.services
