### ISSUE TITLE
Incomplete error handling

### ISSUE THREAD

**Issue by dstd** [jkuri/bore#24]
I suppose there is a dangling error case – it is handled, but the control flow continues as if there was no error, resulting to a nil pointer dereference.

https://github.com/jkuri/bore/blob/master/server/ssh.go#L202

But I'm not sure what is the right way to fix it – `continue` or `break`

**Comment by jkuri** [comment]
you are right, it is continue. can you please open a pr for that?

**Comment by jkuri** [comment]
thanks. next time you can add (closes #24) in commit message atthe end and
issue is closed automatically,
just for your info, its handy.
